### ISSUE TITLE
Error while starting example

### ISSUE THREAD

**Issue by alexd1971** [angel-example/chat#4]
```
$ ANGEL_ENV=production dart bin/server.dart
Unhandled error occurred: Could not connect to localhost:28015.  Error SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 64533
#0      Connection.reconnect.<anonymous closure> (package:rethinkdb_driver2/src/net.dart:125:28)
#1      _rootRunUnary (dart:async/zone.dart:1128)
#2      _CustomZone.runUnary (dart:async/zone.dart:1012)
#3      _FutureListener.handleError (dart:async/future_impl.dart:145)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:648)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:669)
#6      _Future._completeError (dart:async/future_impl.dart:486)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:536)
#8      _rootRun (dart:async/zone.dart:1120)
#9      _CustomZone.run (dart:async/zone.dart:1001)
#10     _CustomZone.runGuarded (dart:async/zone.dart:901)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by thosakwe** [comment]
If you take a look at the stack trace, the error is that you don't have a RethinkDB instance running.

I should modify this tutorial to use a simple JSON file service+pun sub, since not everyone has RethinkDB installed.

**Comment by thosakwe** [comment]
In the meantime, you might consider a more recent example of a WebSocket-powered chat. This one uses Flutter as the client:

https://github.com/angel-example/flutter

**Comment by alexd1971** [comment]
Thank you! Now everything works fine!

**Comment by thosakwe** [comment]
👍
